### ISSUE TITLE
User_dic

### ISSUE THREAD

**Issue by enriavil1** [jhoeljp/Python#4]
https://github.com/jhoeljp/Python/blob/d18375a1b6c872e8a125687194f167293b5ae1d1/Flight_Club/Email_listing.py#L19

The class `User` should be keeping track of all the users created.

**Comment by jhoeljp** [comment]
`Email_listing.py` is an independent system from the flight search system. 
It runs one user a a time, soon to be posted on replit but API call limit has been reached before any testing could be done. 

The class `Users` identifies if this single user is on list by looking at list of all users; using the `user_exists` method.

The list of all users, called `self.data`, is obtained in a `PUT` request made to the google sheet as soon as `Users` object is initialized. So all users are indeed being tracked.
